- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.1
  hooks:
  - id: check-ast
  - id: check-yaml
    exclude: vagga.yaml
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: flake8
    args: [--max-line-length=120]
    exclude: blog/migrations/
  - id: name-tests-test
    args: [--django]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

#- repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
#  sha: v0.3.2
#  hooks:
#  - id: pep257

- repo: git://github.com/Lucas-C/pre-commit-hooks
  sha: v1.1.4
  hooks:
  - id: remove-tabs
